### ISSUE TITLE
EscPosConnectionException: Error queueing USB request

### ISSUE THREAD

**Issue by MustafaAlsihati** [DantSu/ESCPOS-ThermalPrinter-Android#121]
I'm trying to print multiple invoices, but the problem is that when requesting multiple print jobs at the same time, they conflict each other.
Even if I request one job, then another job request came in while the first job is printing, it corrupt the first one and stops completely. 

This problem only occur with USB printing, both TCP/IP and Bluetooth works fine with queuing printing jobs even if I request more than 5 printing jobs at the same time.

this is the error I get:
```
Broken connection: com.dantsu.escposprinter.exceptions.EscPosConnectionException: Error queueing USB request.
        at com.dantsu.escposprinter.connection.usb.UsbConnection.send(UsbConnection.java:87)
        at com.dantsu.escposprinter.EscPosPrinterCommands.cutPaper(EscPosPrinterCommands.java:572)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:166)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:150)
        at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:139)
        at com.cloudapps.pos5.NativeModulesClasses.Printer$1.lambda$onReceive$0$Printer$1(Printer.java:204)
        at com.cloudapps.pos5.NativeModulesClasses.-$$Lambda$Printer$1$V7eUc-UYP8dT2aOwMBTKnWwtNdM.run(Unknown Source:8)
        at java.lang.Thread.run(Thread.java:929)
```

this the code:
```
    @ReactMethod
    public void printUSB(ReadableMap params, Promise promise) {
        try {
            UsbConnection usbConnection = null;

            if (params.getMap("printer").hasKey("usb_path") && params.getMap("printer").getString("usb_path").length() > 0) {
                UsbPrintersConnections usbPrintersConnections = new UsbPrintersConnections(rContext);
                UsbConnection[] usbList = usbPrintersConnections.getList();

                for (UsbConnection device : usbList) {
                    if (device.getDevice().getDeviceName().equals(params.getMap("printer").getString("usb_path"))) {
                        usbConnection = device;
                    }
                }
            } else {
                usbConnection = UsbPrintersConnections.selectFirstConnected(rContext);
            }

            UsbManager usbManager = (UsbManager) rContext.getSystemService(Context.USB_SERVICE);
            if (usbConnection != null && usbManager != null) {
                PendingIntent permissionIntent = PendingIntent.getBroadcast(getCurrentActivity(), 0, new Intent(ACTION_USB_PERMISSION), 0);
                IntentFilter filter = new IntentFilter(ACTION_USB_PERMISSION);
                UsbConnection finalUsbConnection = usbConnection;
                rContext.registerReceiver(new BroadcastReceiver() {
                    public void onReceive(Context context, Intent intent) {
                        String action = intent.getAction();
                        if (ACTION_USB_PERMISSION.equals(action)) {
                            synchronized (this) {
                                try {
                                    UsbManager usbManager = (UsbManager) rContext.getSystemService(Context.USB_SERVICE);
                                    UsbDevice usbDevice = intent.getParcelableExtra(UsbManager.EXTRA_DEVICE);
                                    if (intent.getBooleanExtra(UsbManager.EXTRA_PERMISSION_GRANTED, false)) {
                                        if (usbManager != null && usbDevice != null) {
                                            printUSBJob(params, finalUsbConnection, promise);
                                        }
                                    } else {
                                        Log.e("POS", "No USB permission is granted");
                                    }
                                } catch (Exception e) {
                                    Log.e("POS", "Error occurred, printing did not complete", e);
                                    e.printStackTrace();
                                    promise.reject(e);
                                }
                            }
                        }
                    }
                }, filter);
                usbManager.requestPermission(usbConnection.getDevice(), permissionIntent);
            } else {
                Log.e("POS", "No USB printer connected");
            }
        } catch (Exception e) {
            Log.e("POS", "This is the error: " + Log.getStackTraceString(e), e);
            promise.reject(e);
        }
    }
```
```
    public void printUSBJob(ReadableMap params, UsbConnection finalUsbConnection, Promise promise) {
        try {
            new Thread(() -> {
                try {
                    EscPosPrinter printer = new EscPosPrinter(finalUsbConnection, 203, 70f, 48);

                    // Creation:
                    Bitmap decodedByte = PrintUtils.create(rContext, params);

                    int width = decodedByte.getWidth(), height = decodedByte.getHeight();
                    StringBuilder textToPrint = new StringBuilder();
                    for (int y = 0; y < height; y += 256) {
                        Bitmap bitmap = Bitmap.createBitmap(decodedByte, 0, y, width, (y + 256 >= height) ? height - y : 256);
                        textToPrint.append("[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, bitmap) + "</img>\n");
                    }

                    if (params.getBoolean("kick")) {
                        finalUsbConnection.write(OPEN_DRAWER);
                    }

                    // Print
                    printer.printFormattedTextAndCut(textToPrint.toString());

                    // Finally close connection
                    printer.disconnectPrinter();

                    promise.resolve(true);
                } catch (EscPosConnectionException e) {
                    Log.e("POS", "Broken connection: " + Log.getStackTraceString(e), e);
                    e.printStackTrace();
                    promise.reject(e);
                } catch (EscPosParserException e) {
                    Log.e("POS", "Invalid formatted text: " + Log.getStackTraceString(e), e);
                    e.printStackTrace();
                    promise.reject(e);
                } catch (EscPosEncodingException e) {
                    Log.e("POS", "Bad selected encoding: " + Log.getStackTraceString(e), e);
                    e.printStackTrace();
                    promise.reject(e);
                } catch (Exception e) {
                    Log.e("POS", "Invalid barcode: " + Log.getStackTraceString(e), e);
                    e.printStackTrace();
                    promise.reject(e);
                }
            }).start();
        } catch (Exception e) {
            Log.e("POS", "This is the error: " + Log.getStackTraceString(e), e);
        }
    }
```

I know code is messy so good luck reading that, I'm using it as a native module for react native, If there is any solution do share please.

**Comment by MustafaAlsihati** [comment]
This is the code for TCP/IP printing, it works fine.

```
@ReactMethod
    public void printTCP(ReadableMap params, Promise promise) {
        new Thread(() -> {
            try {
                TcpConnection tcpConnection = new TcpConnection(params.getMap("printer").getString("printer_ip"), params.getMap("printer").getInt("printer_port"));
                EscPosPrinter printer = new EscPosPrinter(tcpConnection, 203, 70f, 48);

                // Creation:
                Bitmap decodedByte = PrintUtils.create(rContext, params);

                int width = decodedByte.getWidth(), height = decodedByte.getHeight();
                StringBuilder textToPrint = new StringBuilder();
                for (int y = 0; y < height; y += 256) {
                    Bitmap bitmap = Bitmap.createBitmap(decodedByte, 0, y, width, (y + 256 >= height) ? height - y : 256);
                    textToPrint.append("[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, bitmap) + "</img>\n");
                }

                // Open Drawer
                if (params.getBoolean("kick")) {
                    tcpConnection.write(OPEN_DRAWER);
                }

                // Print
                printer.printFormattedTextAndCut(textToPrint.toString());

                // Finally close connection
                printer.disconnectPrinter();

                promise.resolve(true);
            } catch (Exception e) {
                Log.e("POS", "Error occurred, Network printing did not complete", e);
                e.printStackTrace();
                promise.reject(e);
            }
        }).start();
    }
```

**Comment by MustafaAlsihati** [comment]
Here is picture of the invoice I print, in the right side is the first one to print, left side is the second to print, after that all remaining printing jobs stops immediately.

Even if i close the connection and wait for few seconds the problem still occurs.

**Comment by MustafaAlsihati** [comment]
I found a solution and it's working with me right now, I changed the code a little bit so that I can unregister the BroadcastReceiver after printing finish. Also, i sent a command to clear buffer, not sure if it helped but since it's doing the job I left it there anyway.

here is the changes I did:
```
...
finalUsbConnection.write(new byte[] {0x1B, 0x40});
finalUsbConnection.send();
printer.printFormattedTextAndCut(textToPrint.toString());
// Unregister broadcast receiver:
rContext.unregisterReceiver(usbReceiver);
...
```
