### ISSUE TITLE
cancelDiscovery needs permission

### ISSUE THREAD

**Issue by yolapop** [DantSu/ESCPOS-ThermalPrinter-Android#234]
Hi,

I am using Android 12 and this is how I tested this library:

```kotlin
val myBluetoothDevice: android.bluetooth.BluetoothDevice = // I queried using my own method
val printer = EscPosPrinter(BluetoothConnection(myBluetoothDevice), 203, 48f, 32)
printer.printFormattedText("Hello world")
```

In the method [`BluetoothConnection.connect()`](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/master/escposprinter/src/main/java/com/dantsu/escposprinter/connection/bluetooth/BluetoothConnection.java#L68), it calls [`BluetoothAdapter.cancelDiscovery()`](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#cancelDiscovery()) which needs runtime permission `Manifest.permission.BLUETOOTH_SCAN`.

Using my code above, it crashes with the log below:

```
java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@b2554085: AdapterService cancelDiscovery
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.bluetooth.IBluetooth$Stub$Proxy.cancelDiscovery(IBluetooth.java:2945)
        at android.bluetooth.BluetoothAdapter.cancelDiscovery(BluetoothAdapter.java:1863)
        at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:68)
```

It is not supposed to crash because I didn't need to discover devices, hence, `BluetoothAdapter.cancelDiscover()` is not supposed to be called inside `BluetoothConnection.connect()`.

**Comment by DantSu** [comment]
Be sure to have `<uses-permission android:name="android.permission.BLUETOOTH" />` and `<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />` in your AndroidMenifest.xml.

**Comment by yolapop** [comment]
Yes, I have those for Android <= 11, but Android 12 doesn't require those permissions. Please take a look at the docs
https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

Below is my manifest

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-feature
        android:name="android.hardware.bluetooth"
        android:required="false" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <!-- Request legacy Bluetooth permissions on older devices. -->
    <uses-permission android:name="android.permission.BLUETOOTH"
        android:maxSdkVersion="30" />
    <uses-permission
        android:name="android.permission.BLUETOOTH_ADMIN"
        android:maxSdkVersion="30" />

</manifest>
```

**Comment by yolapop** [comment]
In my case, I don't need permission `BLUETOOTH_SCAN` because I'm not trying to scan the devices. I only need to connect to the device that I've obtained before

**Comment by DantSu** [comment]
Before connect to a bluetooth device, android documentation say to do a `BluetoothAdapter.cancelDiscovery()` to prevent waiting time and slow connection. So I will not remove this. Add needed permission or do a fork.

**Comment by yolapop** [comment]
Right, the permission seems to be mandatory and it's actually always granted and doesn't need to show permission dialog

**Comment by raajnadar** [comment]
Any help to solve this?

https://github.com/AllInOneYT/react-native-thermal-printer/issues/44

**Comment by zenemy** [comment]
Hi, is there any solution to this? im facing the same issue
