### ISSUE TITLE
com.dantsu.escposprinter.connection.DeviceConnection com.dantsu.escposprinter.connection.DeviceConnection.connect()' on a null object reference

### ISSUE THREAD

**Issue by dharmik953** [DantSu/ESCPOS-ThermalPrinter-Android#247]
I want to print a bitmap can I do with this library? I have tried the app in the library.

this is my logcat

> 
```
2022-01-21 09:15:12.265 29376-29376/com.dharmik953.test_image E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dharmik953.test_image, PID: 29376


  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
        at com.dharmik953.test_image.MainActivity.lambda$onCreate$0$com-dharmik953-test_image-MainActivity(MainActivity.java:89)
        at com.dharmik953.test_image.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7189)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View.performClickInternal(View.java:7166)
        at android.view.View.access$3500(View.java:819)
        at android.view.View$PerformClick.run(View.java:27682)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

i got this logcat with the use of this code.

```java
            // convert drawable to bitmap
            int targetWidth = 383; // 48mm printing zone with 203dpi => 383px
            Bitmap originalBitmap = BitmapFactory.decodeResource(getContext().getResources(), R.drawable.yellow);
            Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
                    originalBitmap,
                    targetWidth,
                    Math.round(((float) originalBitmap.getHeight()) * ((float) targetWidth) / ((float) originalBitmap.getWidth())),
                    true
            );

            EscPosPrinterCommands printerCommands = new EscPosPrinterCommands(BluetoothPrintersConnections.selectFirstPaired());
            try {
                printerCommands.connect();
                printerCommands.reset();
                printerCommands.printImage(EscPosPrinterCommands.bitmapToBytes(rescaledBitmap));
                printerCommands.feedPaper(50);
//                printerCommands.cutPaper();
            } catch (EscPosConnectionException e) {
                e.printStackTrace();
            }
```

this is my code that i used for print JPG and PNG images. with this code nothing happened. even can't see any thing in the logcat.

```java
           EscPosPrinter printer = null;
            try {
                printer = new EscPosPrinter(BluetoothPrintersConnections.selectFirstPaired(), 203, 48f, 32);
            } catch (EscPosConnectionException e) {
                e.printStackTrace();
            }
            try {
                assert printer != null;
                printer
                        .printFormattedText(
                                "[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, this.getApplicationContext().getResources().getDrawableForDensity(R.drawable.yellowmen, DisplayMetrics.DENSITY_MEDIUM))+"</img>\n" +
                                        "[L]\n" +
                                        "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
                                        "[L]\n" +
                                        "[C]================================\n" +
                                        "[L]\n" +
                                        "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
                                        "[L]  + Size : S\n" +
                                        "[L]\n" +
                                        "[L]<b>AWESOME HAT</b>[R]24.99e\n" +
                                        "[L]  + Size : 57/58\n" +
                                        "[L]\n" +
                                        "[C]--------------------------------\n" +
                                        "[R]TOTAL PRICE :[R]34.98e\n" +
                                        "[R]TAX :[R]4.23e\n" +
                                        "[L]\n" +
                                        "[C]================================\n" +
                                        "[L]\n" +
                                        "[L]<font size='tall'>Customer :</font>\n" +
                                        "[L]Raymond DUPONT\n" +
                                        "[L]5 rue des girafes\n" +
                                        "[L]31547 PERPETES\n" +
                                        "[L]Tel : +33801201456\n" +
                                        "[L]\n" +
                                        "[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
                                        "[C]<qrcode size='20'>http://www.developpeur-web.dantsu.com/</qrcode>"
                        );

            } catch (EscPosConnectionException e) {
                e.printStackTrace();
            } catch (EscPosParserException e) {
                e.printStackTrace();
            } catch (EscPosEncodingException e) {
                e.printStackTrace();
            } catch (EscPosBarcodeException e) {
                e.printStackTrace();
            }
```

**Comment by DantSu** [comment]
It's normal to have 2 differents ressources names ? R.drawable.yellowmen <> R.drawable.yellow
Can you share me the image you want to print ?

**Comment by dharmik953** [comment]
![yellowmen](https://user-images.githubusercontent.com/69726977/150625226-3dfa80c8-9cbd-482b-adc1-57b6f923abc0.jpg)
this is my image

**Comment by dharmik953** [comment]
no yellowmen id PNG file and yellow is JPG file. i used one by one.
