### ISSUE TITLE
Wait for how long to accept next printing command

### ISSUE THREAD

**Issue by fWd82** [DantSu/ESCPOS-ThermalPrinter-Android#256]
Hi, 
Do we need to wait for certain time to send another print request to printer? The second time alertdialog  says: 

**No printer found.** 

But trying after three / four seconds (three to four attemps) it accepts next printing command request.

**Stack Trace:** 
```
D/TAG: DocumentSnapshot added with ID: dUqsxw4mBb8zzygnVKht
D/TAG: ====================== <<< ONE REQUEST DONE!
D/AppTurboService:  getSettingSupport resullt = false mSettingCloudEnable = true
D/ViewRootImpl[Printing in progress]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
I/chatty: uid=10224(com.test.test) identical 2 lines
D/AppTurboService:  getSettingSupport resullt = false mSettingCloudEnable = true
I/InputTransport: Create ARC handle: 0xb4000070fc7e9fe0
    InputConsumer create TRAN_APPTURBO_ENABLE disable
W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
W/System.err: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
        at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:758)
        at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:711)
        at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:409)
        at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:69)
        at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
        at com.test.test.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:30)
        at com.test.test.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:9)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
D/BluetoothSocket: close() this: android.bluetooth.BluetoothSocket@cded95c, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@a44c465, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@e3c953amSocket: android.net.LocalSocket@a1f65eb impl:android.net.LocalSocketImpl@f2e2f48 fd:java.io.FileDescriptor@2c241e1, mSocketState: INIT
W/System.err: com.dantsu.escposprinter.exceptions.EscPosConnectionException: Unable to connect to bluetooth device.
        at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:75)
        at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
        at com.test.test.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:30)
        at com.test.test.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:9)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
D/View: [Warning] assignParent to null: this = DecorView@38c75c7[Printing in progress]
I/InputTransport: Destroy ARC handle: 0xb4000070fc7e9fe0
D/AppTurboService:  getSettingSupport resullt = false mSettingCloudEnable = true
D/ViewRootImpl[MainActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
I/chatty: uid=10224(com.test.test) identical 2 lines
D/AppTurboService:  getSettingSupport resullt = false mSettingCloudEnable = true
I/InputTransport: Create ARC handle: 0xb4000070fc7e8930
    InputConsumer create TRAN_APPTURBO_ENABLE disable
I/Async.OnPrintFinished: AsyncEscPosPrint.OnPrintFinished : An error occurred !
D/View: [Warning] assignParent to null: this = DecorView@66601b6[MainActivity]
W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
I/InputTransport: Destroy ARC handle: 0xb4000070fc7e8930
```
**Logcat:**
```
2022-02-11 16:00:13.245 1733-1733/? D/TAG: updateClearButton: cccc
2022-02-11 16:00:31.314 1733-1733/? D/TAG: updateClearButton: cccc
2022-02-11 16:00:37.354 1733-1733/? D/TAG: updateClearButton: cccc
2022-02-11 16:00:40.366 1733-1733/? D/TAG: updateClearButton: cccc
```

Do I need to detch anything? Remeber I am executing next command after I hearing: 
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/007dc9f0f47b98157d6f5550a7867e40eda70ce0/app/src/main/java/com/dantsu/thermalprinter/MainActivity.java#L153

```
                       @Override
                        public void onSuccess(AsyncEscPosPrinter asyncEscPosPrinter) {
                            Log.i("Async.OnPrintFinished", "AsyncEscPosPrint.OnPrintFinished : Print is finished !");
                            insertDataToFirestore();
                        }
```

**EDIT:**
```

I/InputTransport: Destroy ARC handle: 0xb4000070fc7dee20
W/qbal.lihparkin: Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
W/qbal.lihparkin: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
W/qbal.lihparkin: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
W/qbal.lihparkin: Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
W/qbal.lihparkin: Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
    Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
D/TAG: DocumentSnapshot added with ID: IThBhwCukx9hHLPw2nA3
D/TAG: ======================
D/AppTurboService:  getSettingSupport resullt = false mSettingCloudEnable = true
D/ViewRootImpl[Printing in progress]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
I/chatty: uid=10224(com.test.test) identical 2 lines
D/AppTurboService:  getSettingSupport resullt = false mSettingCloudEnable = true
I/InputTransport: Create ARC handle: 0xb4000070fc7f2080
    InputConsumer create TRAN_APPTURBO_ENABLE disable
W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
W/System.err: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
        at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:758)
        at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:711)
        at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:409)
        at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:69)
        at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
        at com.test.test.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:30)
W/System.err:     at com.test.test.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:9)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
D/BluetoothSocket: close() this: android.bluetooth.BluetoothSocket@d004504, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@33ccaed, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@704cd22mSocket: android.net.LocalSocket@dd7e3b3 impl:android.net.LocalSocketImpl@bbead70 fd:java.io.FileDescriptor@da828e9, mSocketState: INIT
W/System.err: com.dantsu.escposprinter.exceptions.EscPosConnectionException: Unable to connect to bluetooth device.
        at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:75)
W/System.err:     at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
        at com.test.test.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:30)
        at com.test.test.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:9)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
D/View: [Warning] assignParent to null: this = DecorView@6b9309c[Printing in progress]
I/InputTransport: Destroy ARC handle: 0xb4000070fc7f2080
D/AppTurboService:  getSettingSupport resullt = false mSettingCloudEnable = true
D/ViewRootImpl[MainActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
I/chatty: uid=10224(com.test.test) identical 2 lines
D/AppTurboService:  getSettingSupport resullt = false mSettingCloudEnable = true
I/InputTransport: Create ARC handle: 0xb4000070fc7f18d0
    InputConsumer create TRAN_APPTURBO_ENABLE disable
I/Async.OnPrintFinished: AsyncEscPosPrint.OnPrintFinished : An error occurred !
D/View: [Warning] assignParent to null: this = DecorView@b9c12ff[MainActivity]
W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
I/InputTransport: Destroy ARC handle: 0xb4000070fc7f18d0
I/qbal.lihparkin: Compiler allocated 4303KB to compile void android.view.ViewRootImpl.performTraversals()

```

The app is working after dismissing the **No Printer** dialogue box for two to three attempts. I don't know what the problem is. 

**Devices:** 
**Samsung Galaxy E5** Android 4.4.4
**Techno Camon 17** Android 11
**Speed-X** BT500m

_(I doubt, It was working fine few days ago)_

**Comment by fWd82** [comment]
With reference to commit [b0c0b40116fcae1454e67f45fda81990e33efe55](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/commit/b0c0b40116fcae1454e67f45fda81990e33efe55) and [comment](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/commit/b0c0b40116fcae1454e67f45fda81990e33efe55#commitcomment-66920512) by @DantSu . By adding these two lines in file [AsyncEscPosPrint.java](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/aa3d9b4e6fab428981b9a1f9612cff56db08e4a0/app/src/main/java/com/dantsu/thermalprinter/async/AsyncEscPosPrint.java#L45) solved the problem:

```
Thread.sleep(1000);
printer.disconnectPrinter();
```

The whole code for the block in **AsyncEscPosPrint.java** looks like this: 

```
protected PrinterStatus doInBackground(AsyncEscPosPrinter... printersData) {
        if (printersData.length == 0) {
            return new PrinterStatus(null, AsyncEscPosPrint.FINISH_NO_PRINTER);
        }

        this.publishProgress(AsyncEscPosPrint.PROGRESS_CONNECTING);

        AsyncEscPosPrinter printerData = printersData[0];

        try {
            DeviceConnection deviceConnection = printerData.getPrinterConnection();

            if(deviceConnection == null) {
                return new PrinterStatus(null, AsyncEscPosPrint.FINISH_NO_PRINTER);
            }

            EscPosPrinter printer = new EscPosPrinter(
                    deviceConnection,
                    printerData.getPrinterDpi(),
                    printerData.getPrinterWidthMM(),
                    printerData.getPrinterNbrCharactersPerLine(),
                    new EscPosCharsetEncoding("windows-1252", 16)
            );

            this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTING);
            printer.printFormattedTextAndCut(printerData.getTextToPrint());
            this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTED);

            // new lines
            Thread.sleep(1000);
            printer.disconnectPrinter();

        } catch (EscPosConnectionException e) {
            e.printStackTrace();
            return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_PRINTER_DISCONNECTED);
        } catch (EscPosParserException e) {
            e.printStackTrace();
            return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_PARSER_ERROR);
        } catch (EscPosEncodingException e) {
            e.printStackTrace();
            return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_ENCODING_ERROR);
        } catch (EscPosBarcodeException e) {
            e.printStackTrace();
            return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_BARCODE_ERROR);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_SUCCESS);
    }
```

Solved! Thank You.
