### ISSUE TITLE
Not Working on Elzab S200M

### ISSUE THREAD

**Issue by Heroes84** [DantSu/ESCPOS-ThermalPrinter-Android#261]
Hi i try you library with that thermal printer https://www.elzab.com.pl/en/receipt-printers/elz-s200m
I properly configure it by WiFi setup IP address and checked it by tool provide by manufacturer, also run sample code from him and it working. Second I want use this library because has better api, but when configure with. the same ip address and port see in logcat:
```
022-02-23 18:24:29.437 23193-23304/com.dantsu.thermalprinter W/System.err: java.net.SocketTimeoutException: failed to connect to /192.168.0.107 (port 9100) from /10.0.2.16 (port 34922) after 30ms
2022-02-23 18:24:29.437 23193-23304/com.dantsu.thermalprinter W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
2022-02-23 18:24:29.438 23193-23304/com.dantsu.thermalprinter W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:135)
2022-02-23 18:24:29.438 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2022-02-23 18:24:29.438 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2022-02-23 18:24:29.438 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2022-02-23 18:24:29.438 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2022-02-23 18:24:29.438 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2022-02-23 18:24:29.438 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.net.Socket.connect(Socket.java:621)
2022-02-23 18:24:29.438 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.escposprinter.connection.tcp.TcpConnection.connect(TcpConnection.java:63)
2022-02-23 18:24:29.439 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.escposprinter.connection.tcp.TcpConnection.connect(TcpConnection.java:12)
2022-02-23 18:24:29.440 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.escposprinter.EscPosPrinterCommands.connect(EscPosPrinterCommands.java:240)
2022-02-23 18:24:29.440 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:54)
2022-02-23 18:24:29.440 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:40)
2022-02-23 18:24:29.440 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.thermalprinter.async.AsyncEscPosPrint.doInBackground(AsyncEscPosPrint.java:65)
2022-02-23 18:24:29.440 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.thermalprinter.async.AsyncEscPosPrint.doInBackground(AsyncEscPosPrint.java:18)
2022-02-23 18:24:29.441 23193-23304/com.dantsu.thermalprinter W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
2022-02-23 18:24:29.441 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-02-23 18:24:29.441 23193-23304/com.dantsu.thermalprinter W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
2022-02-23 18:24:29.441 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-02-23 18:24:29.441 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-02-23 18:24:29.442 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.lang.Thread.run(Thread.java:919)
2022-02-23 18:24:29.442 23193-23304/com.dantsu.thermalprinter W/System.err: com.dantsu.escposprinter.exceptions.EscPosConnectionException: Unable to connect to TCP device.
2022-02-23 18:24:29.443 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.escposprinter.connection.tcp.TcpConnection.connect(TcpConnection.java:69)
2022-02-23 18:24:29.443 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.escposprinter.connection.tcp.TcpConnection.connect(TcpConnection.java:12)
2022-02-23 18:24:29.443 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.escposprinter.EscPosPrinterCommands.connect(EscPosPrinterCommands.java:240)
2022-02-23 18:24:29.444 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:54)
2022-02-23 18:24:29.444 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:40)
2022-02-23 18:24:29.444 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.thermalprinter.async.AsyncEscPosPrint.doInBackground(AsyncEscPosPrint.java:65)
2022-02-23 18:24:29.444 23193-23304/com.dantsu.thermalprinter W/System.err:     at com.dantsu.thermalprinter.async.AsyncEscPosPrint.doInBackground(AsyncEscPosPrint.java:18)
2022-02-23 18:24:29.444 23193-23304/com.dantsu.thermalprinter W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
2022-02-23 18:24:29.445 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-02-23 18:24:29.445 23193-23304/com.dantsu.thermalprinter W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
2022-02-23 18:24:29.445 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-02-23 18:24:29.445 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-02-23 18:24:29.446 23193-23304/com.dantsu.thermalprinter W/System.err:     at java.lang.Thread.run(Thread.java:919)
```
![Screenshot_1645637073](https://user-images.githubusercontent.com/5124243/155373191-dbdd9767-8427-4c6d-83ba-37128978b862.png)

**Comment by DantSu** [comment]
Other subject, ELZ-S200M not seems to be an ESC/POS printer, so commands may not be reconized.

> `failed to connect to /192.168.0.107 (port 9100) from /10.0.2.16 (port 34922)`

Your android device try to connect to a local address with a non local interface like is not on the same network. Have you try to keep only wifi, stop 4G / 5G and other network interfaces.

**Comment by Heroes84** [comment]
Thank you for you replay, sorry and now don't have the printer, but problem isn't in the connection setup (my android device was a emulator that was on the same wifi network) but like you write problem was in the protocol to work with printer I used manufacturer skd that after connecting send this bytes:
//java code
`    public static byte[] initializePrinter() {
        byte[] data = new byte[]{27, 64};
        return data;
    }`
