### ISSUE TITLE
I'm getting ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by frank240889** [DantSu/ESCPOS-ThermalPrinter-Android#344]
hello when I parse the  text into lines using and then iterate over the elements, I'm getting the next exception:

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=3 srcPos=0 dst.length=9 dstPos=35 length=3
       at java.lang.System.arraycopy(System.java:524)
       at com.dantsu.escposprinter.connection.DeviceConnection.write(DeviceConnection.java:35)
       at com.dantsu.escposprinter.EscPosPrinterCommands.printText(EscPosPrinterCommands.java:459)
       at com.dantsu.escposprinter.textparser.PrinterTextParserString.print(PrinterTextParserString.java:57)
       at com.dantsu.escposprinter.textparser.PrinterTextParserString.print(PrinterTextParserString.java:11)

I can not validate the length because is inside the library.

**Comment by DantSu** [comment]
Send me the text you have to parse.

**Comment by frank240889** [comment]
Hello and thanks for your quick response.

I really don't know, because is happening with different texts, is not a very frequently bug but is a bit weird. Let check if I can collect any of those text when app crash.

**Comment by aoatstudios** [comment]
I'm also having this problem...
But when I'm remove this line

"[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, this.getApplicationContext().getResources().getDrawableForDensity(R.drawable.logo, DisplayMetrics.DENSITY_MEDIUM))+"</img>\n" +
       it works fine
