### ISSUE TITLE
Can't connect / print anymore via bluetooth

### ISSUE THREAD

**Issue by TomasBozek** [DantSu/ESCPOS-ThermalPrinter-Android#355]
Hello, 
I am experiencing issues with this library. I was successfully using this lib to print receipts over Bluetooth. Currently, lib produces exceptions and I am not able to print anything. My printer is paired and works in mode (I guess every one of them does) when you don't see it as connected, just paired. Whatever, the essential thing is this lib sees my printer and so do some other apps I downloaded from the play store to try if they are able to print something. To my confusion, other apps can easily print whatever on my printer.

I suspected an issue with coroutines, threads, or permissions and try everything... but nothing worked. I am using an updated google pixel 6 XL (I also tested this on an older google pixel 2 xl). My project is up to date and I am using the latest version of this lib.

Could you explain what's wrong or if you need to release a fix?  Thank you for any help.

Problem is with selectFirstPaired(). I am checking for permissions before that and only continue when they are all granted. It's not working even in the app on create or activity on create. I am clueless.

```
            try {
                val connection = BluetoothPrintersConnections.selectFirstPaired()
                val printer =
                    EscPosPrinter(
                        connection,
                        203,
                        48f,
                        32
                    )

                printer.printFormattedTextAndCut(command.formattedPrintText, 10f)
                printer.disconnectPrinter()
            } catch (t: Throwable) {
                t.printStackTrace()
            }
```

```
12:58:04.666  W  java.io.IOException: read failed, socket might closed or timeout, read ret: -1
12:58:04.666  W  	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:815)
12:58:04.666  W  	at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:829)
12:58:04.666  W  	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:442)
12:58:04.666  W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:69)
12:58:04.666  W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
12:58:04.666  W  	at app.activity.AppActivity.onPrintCmd(AppActivity.kt:220)
12:58:04.666  W  	at app.activity.AppActivity.access$onPrintCmd(AppActivity.kt:53)
12:58:04.666  W  	at app.activity.AppActivity$onCreate$1$1$1$4$1$1.invokeSuspend(AppActivity.kt:136)
12:58:04.666  W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12:58:04.666  W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12:58:04.666  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
12:58:04.666  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
12:58:04.666  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
12:58:04.666  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)


12:58:04.667  D  close() this: android.bluetooth.BluetoothSocket@1585ee2, channel: -1, mSocketIS: 
android.net.LocalSocketImpl$SocketInputStream@4557273, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@932f530,
 mSocket: android.net.LocalSocket@48735a9 impl:android.net.LocalSocketImpl@9a1872e fd:java.io.FileDescriptor@c8ac2cf, 
mSocketState: INIT


12:58:04.667  W  com.dantsu.escposprinter.exceptions.EscPosConnectionException: Unable to connect to bluetooth device.
12:58:04.667  W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:75)
12:58:04.667  W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
12:58:04.667  W  	at app.activity.AppActivity.onPrintCmd(AppActivity.kt:220)
12:58:04.667  W  	at app.activity.AppActivity.access$onPrintCmd(AppActivity.kt:53)
12:58:04.667  W  	at app.activity.AppActivity$onCreate$1$1$1$4$1$1.invokeSuspend(AppActivity.kt:136)
12:58:04.667  W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12:58:04.667  W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12:58:04.667  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
12:58:04.668  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
12:58:04.668  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
12:58:04.668  W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
12:58:05.023  V  Inactivity, disconnecting from the service
```

**Comment by TomasBozek** [comment]
Well. i tried to fix it my self.

I end up with AppBluetoothConnection(device: BluetoothDevice) : BluetoothConnection(device) and used it to init printer.

```
class AppBluetoothConnection(device: BluetoothDevice) : BluetoothConnection(device) {

    var btSocket:BluetoothSocket? = null

    var bufferedOutputStream:BufferedOutputStream? = null

    @SuppressLint("MissingPermission")
    override fun connect(): BluetoothConnection {
        if (this.isConnected) {
            return this
        } else if (this.device == null) {
            throw Throwable("AppBluetoothConnection - Bluetooth device is not connected.")
        } else {
            val uuid = UUID.fromString("00001101-0000-1000-8000-00805F9B34FB")
            try {
                val socket: BluetoothSocket? by lazy(LazyThreadSafetyMode.NONE) {
                    device.createRfcommSocketToServiceRecord(uuid)
                }
                socket?.let {
                    Timber.d("AppBluetoothConnection - BluetoothSocket connecting")
                    btSocket = it
                    btSocket?.connect()
                    Timber.d("AppBluetoothConnection - BluetoothSocket connected = ${it.isConnected}")
                    val stream = BufferedOutputStream(it.outputStream)
                    bufferedOutputStream = stream

                    this.outputStream = stream
                    //this.data = byteArrayOf(0)
                }
                return this
            } catch (var4: IOException) {
                var4.printStackTrace()
                this.disconnect()
                throw Throwable("AppBluetoothConnection - Unable to connect to bluetooth device.")
            }
        }
    }

    override fun send(addWaitingTime: Int) {
        if (!this.isConnected) {
            throw Throwable("AppBluetoothConnection - Unable to send data to device.")
        } else {
            try {
                bufferedOutputStream?.write(data)
                bufferedOutputStream?.flush()
                val waitingTime = addWaitingTime + data.size / 16
                data = ByteArray(0)
                if (waitingTime > 0) {
                    Thread.sleep(waitingTime.toLong())
                }
            } catch (var3: InterruptedException) {
                var3.printStackTrace()
                throw EscPosConnectionException(var3.message)
            } catch (var3: IOException) {
                var3.printStackTrace()
                throw EscPosConnectionException(var3.message)
            }
        }
    }

    override fun isConnected(): Boolean {
        return btSocket != null && btSocket?.isConnected == true && this.bufferedOutputStream != null
    }

    override fun disconnect(): BluetoothConnection {
        data = ByteArray(0)
        if (outputStream != null) {
            try {
                bufferedOutputStream?.close()
                outputStream.close()
            } catch (var3: IOException) {
                var3.printStackTrace()
            }
            outputStream = null
            bufferedOutputStream = null
        }

        if (btSocket != null) {
            try {
                btSocket?.close()
            } catch (var2: IOException) {
                var2.printStackTrace()
            }
            btSocket = null
        }
        return this
    }
}
```

after the permissions check, executing one time print of formatted text
```
else {
      Timber.d("bluetooth is OK")
      val pairedDevices: Set<BluetoothDevice>? =
          bluetoothAdapter.bondedDevices
      var printDevice: BluetoothDevice? = null
      pairedDevices?.forEach { device ->
          val deviceName = device.name
          val deviceHardwareAddress = device.address // MAC address
          Timber.d(deviceName)
          Timber.d(deviceHardwareAddress)
          if (deviceName == "Restaurant Printer") printDevice = device
      }
      printDevice?.let {
          Timber.d(" *** printer found *** ")
          bluetoothAdapter.cancelDiscovery()
          val socket: BluetoothSocket? by lazy(LazyThreadSafetyMode.NONE) {
              it.createRfcommSocketToServiceRecord(java.util.UUID.fromString("00001101-0000-1000-8000-00805F9B34FB"))
          }
          GlobalScope.launch(Dispatchers.IO) {
              try {
                  val list = BluetoothConnections().list
                  list?.forEach {
                      Timber.d(it.device.address)
                      if (it.device.name == "Restaurant Printer") {
                          val connection = AppBluetoothConnection(it.device)
                          Timber.d("AppBluetoothConnection connected = ${connection.isConnected}")
                          val printer = EscPosPrinter(
                              connection,
                              203,
                              48f,
                              32,
                              EscPosCharsetEncoding("windows-1250", 72)
                          )
  
                          printer.printFormattedText(command.formattedPrintText)
                          printer.disconnectPrinter()
                      }
                  }
              } catch (e: Throwable) {
                  Timber.e(e)
                  socket?.close()
              } finally {
  
              }
          }
      }
 }
```

**Comment by DantSu** [comment]
Thank you for your work ! That will be very helpful for many coders :)

**Comment by Substractive** [comment]
I made example for Ionic 6 capacitor + angular while having same issue with this, and I managed to make it print without losing connection. Tested on android only but feel free to take a look.
Using only Bluetooth Serial and EscPosEncoder.
Hope it helps someone.
[Demo](https://github.com/Substractive/ionic-capacitor-esc-pos-bluetooth)

**Comment by MoustafaElsaghier** [comment]
@TomasBozek this cause exception

> Uncaught exception in binary message listener
                                        com.dantsu.escposprinter.exceptions.EscPosConnectionException: flush is called on null OutputStream
                                        	at com.example.printing_plugin.AppBluetoothConnection.send(AppBluetoothConnection.kt:67)
                                        	at com.dantsu.escposprinter.connection.DeviceConnection.send(DeviceConnection.java:44)
                                        	at com.dantsu.escposprinter.EscPosPrinterCommands.newLine(EscPosPrinterCommands.java:697)
                                        	at com.dantsu.escposprinter.EscPosPrinterCommands.newLine(EscPosPrinterCommands.java:682)
                                        	at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:135)
                                        	at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:176)
                                        	at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:161)
                                        	at com.dantsu.escposprinter.EscPosPrinter.printFormattedTextAndCut(EscPosPrinter.java:150)
                                   

can you help with that, please?
as it's causing print the first line only
