### ISSUE TITLE
Not printing all the time

### ISSUE THREAD

**Issue by Mayranit** [DantSu/ESCPOS-ThermalPrinter-Android#356]
**After a successful print, If I try to print again. It fails. Next time it prints. Below are the error logs I get.** 

2022-11-09 17:03:56.848 27656-27656 DecorView               com.dantsu.thermalprinter            E  [CIPHERLAB] call UnregisterReceiver <---, this = DecorView@a4f2b5d[]
2022-11-09 17:03:56.864 27656-27656 InputEventReceiver      com.dantsu.thermalprinter            W  Attempted to finish an input event but the input event receiver has already been disposed.
2022-11-09 17:03:58.253 27656-27656 DecorView               com.dantsu.thermalprinter            E  [CIPHERLAB] call RegisterReceiver ---> , this = DecorView@4f73e82[Printing in progress]
2022-11-09 17:03:58.346 27656-27886 BluetoothAdapter        com.dantsu.thermalprinter            W  getBluetoothService() called with no BluetoothManagerCallback
2022-11-09 17:03:58.383 27656-27661 zygote64                com.dantsu.thermalprinter            I  Do full code cache collection, code=250KB, data=188KB
2022-11-09 17:03:58.384 27656-27661 zygote64                com.dantsu.thermalprinter            I  After code cache collection, code=250KB, data=157KB
2022-11-09 17:03:58.965 27656-27886 System.err              com.dantsu.thermalprinter            W  java.io.IOException: read failed, socket might closed or timeout, read ret: -1
2022-11-09 17:03:58.966 27656-27886 System.err              com.dantsu.thermalprinter            W  	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:686)
2022-11-09 17:03:58.968 27656-27886 System.err              com.dantsu.thermalprinter            W  	at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:645)
2022-11-09 17:03:58.969 27656-27886 System.err              com.dantsu.thermalprinter            W  	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:379)
2022-11-09 17:03:58.969 27656-27886 System.err              com.dantsu.thermalprinter            W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:69)
2022-11-09 17:03:58.970 27656-27886 System.err              com.dantsu.thermalprinter            W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
2022-11-09 17:03:58.971 27656-27886 System.err              com.dantsu.thermalprinter            W  	at com.dantsu.thermalprinter.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:30)
2022-11-09 17:03:58.972 27656-27886 System.err              com.dantsu.thermalprinter            W  	at com.dantsu.thermalprinter.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:9)
2022-11-09 17:03:58.973 27656-27886 System.err              com.dantsu.thermalprinter            W  	at android.os.AsyncTask$2.call(AsyncTask.java:333)
2022-11-09 17:03:58.974 27656-27886 System.err              com.dantsu.thermalprinter            W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-11-09 17:03:58.975 27656-27886 System.err              com.dantsu.thermalprinter            W  	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2022-11-09 17:03:58.975 27656-27886 System.err              com.dantsu.thermalprinter            W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2022-11-09 17:03:58.976 27656-27886 System.err              com.dantsu.thermalprinter            W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2022-11-09 17:03:58.976 27656-27886 System.err              com.dantsu.thermalprinter            W  	at java.lang.Thread.run(Thread.java:764)
2022-11-09 17:03:58.980 27656-27886 BluetoothSocket         com.dantsu.thermalprinter            D  close() this: android.bluetooth.BluetoothSocket@6804c32, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@c83dd83, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@7f56b00mSocket: android.net.LocalSocket@c18bf39 impl:android.net.LocalSocketImpl@fe2f97e fd:java.io.FileDescriptor@11ccedf, mSocketState: INIT
2022-11-09 17:03:58.982 27656-27886 System.err              com.dantsu.thermalprinter            W  com.dantsu.escposprinter.exceptions.EscPosConnectionException: Unable to connect to bluetooth device.
2022-11-09 17:03:58.984 27656-27886 System.err              com.dantsu.thermalprinter            W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:75)
2022-11-09 17:03:58.985 27656-27886 System.err              com.dantsu.thermalprinter            W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
2022-11-09 17:03:58.986 27656-27886 System.err              com.dantsu.thermalprinter            W  	at com.dantsu.thermalprinter.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:30)
2022-11-09 17:03:58.986 27656-27886 System.err              com.dantsu.thermalprinter            W  	at com.dantsu.thermalprinter.async.AsyncBluetoothEscPosPrint.doInBackground(AsyncBluetoothEscPosPrint.java:9)
2022-11-09 17:03:58.987 27656-27886 System.err              com.dantsu.thermalprinter            W  	at android.os.AsyncTask$2.call(AsyncTask.java:333)
2022-11-09 17:03:58.987 27656-27886 System.err              com.dantsu.thermalprinter            W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-11-09 17:03:58.988 27656-27886 System.err              com.dantsu.thermalprinter            W  	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2022-11-09 17:03:58.988 27656-27886 System.err              com.dantsu.thermalprinter            W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2022-11-09 17:03:58.989 27656-27886 System.err              com.dantsu.thermalprinter            W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2022-11-09 17:03:58.989 27656-27886 System.err              com.dantsu.thermalprinter            W  	at java.lang.Thread.run(Thread.java:764)
2022-11-09 17:03:59.001 27656-27656 DecorView               com.dantsu.thermalprinter            E  [CIPHERLAB] call UnregisterReceiver <---, this = DecorView@4f73e82[Printing in progress]
2022-11-09 17:03:59.023 27656-27656 DecorView               com.dantsu.thermalprinter            E  [CIPHERLAB] call RegisterReceiver ---> , this = DecorView@af59a18[]
2022-11-09 17:03:59.100 27656-27656 Async.OnPrintFinished   com.dantsu.thermalprinter            E  AsyncEscPosPrint.OnPrintFinished : An error occurred !

**Comment by Sihui128** [comment]
If it prints sometimes and sometimes not, you can solve this by attempt multiple times until the print succeed

**Comment by NRicode** [comment]
> If it prints sometimes and sometimes not, you can solve this by attempt multiple times until the print succeed



> Has this ever been solved? I'm having the same problem. Thanks!

This is a persistent bug that has existed for over a year. switch to version 2.0.9 for consistent printing.

**Comment by NandoDev1997** [comment]
I found a solution to the problem, in the AsyncEscPosPrint file in the doInBackground method at the end of the try add the following line:
printer.disconnectPrinter(); 

    protected PrinterStatus doInBackground(AsyncEscPosPrinter... printersData) {
        if (printersData.length == 0) {
            return new PrinterStatus(null, AsyncEscPosPrint.FINISH_NO_PRINTER);
        }

        this.publishProgress(AsyncEscPosPrint.PROGRESS_CONNECTING);

        AsyncEscPosPrinter printerData = printersData[0];

        try {
            DeviceConnection deviceConnection = printerData.getPrinterConnection();

            if(deviceConnection == null) {
                return new PrinterStatus(null, AsyncEscPosPrint.FINISH_NO_PRINTER);
            }

            EscPosPrinter printer = new EscPosPrinter(
                    deviceConnection,
                    printerData.getPrinterDpi(),
                    printerData.getPrinterWidthMM(),
                    printerData.getPrinterNbrCharactersPerLine(),
                    new EscPosCharsetEncoding("windows-1252", 16)
            );

            // printer.useEscAsteriskCommand(true);

            this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTING);

            String[] textsToPrint = printerData.getTextsToPrint();

            for(String textToPrint : textsToPrint) {
                printer.printFormattedTextAndCut(textToPrint);
                Thread.sleep(500);
            }

            this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTED);


            **printer.disconnectPrinter();**

        } catch (EscPosConnectionException e) {
            e.printStackTrace();
            return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_PRINTER_DISCONNECTED);
        } catch (EscPosParserException e) {
            e.printStackTrace();
            return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_PARSER_ERROR);
        } catch (EscPosEncodingException e) {
            e.printStackTrace();
            return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_ENCODING_ERROR);
        } catch (EscPosBarcodeException e) {
            e.printStackTrace();
            return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_BARCODE_ERROR);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_SUCCESS);
    }

**Comment by tucomel** [comment]
> I found a solution to the problem, in the AsyncEscPosPrint file in the doInBackground method at the end of the try add the following line: printer.disconnectPrinter();
> 
> ```
> protected PrinterStatus doInBackground(AsyncEscPosPrinter... printersData) {
>     if (printersData.length == 0) {
>         return new PrinterStatus(null, AsyncEscPosPrint.FINISH_NO_PRINTER);
>     }
> 
>     this.publishProgress(AsyncEscPosPrint.PROGRESS_CONNECTING);
> 
>     AsyncEscPosPrinter printerData = printersData[0];
> 
>     try {
>         DeviceConnection deviceConnection = printerData.getPrinterConnection();
> 
>         if(deviceConnection == null) {
>             return new PrinterStatus(null, AsyncEscPosPrint.FINISH_NO_PRINTER);
>         }
> 
>         EscPosPrinter printer = new EscPosPrinter(
>                 deviceConnection,
>                 printerData.getPrinterDpi(),
>                 printerData.getPrinterWidthMM(),
>                 printerData.getPrinterNbrCharactersPerLine(),
>                 new EscPosCharsetEncoding("windows-1252", 16)
>         );
> 
>         // printer.useEscAsteriskCommand(true);
> 
>         this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTING);
> 
>         String[] textsToPrint = printerData.getTextsToPrint();
> 
>         for(String textToPrint : textsToPrint) {
>             printer.printFormattedTextAndCut(textToPrint);
>             Thread.sleep(500);
>         }
> 
>         this.publishProgress(AsyncEscPosPrint.PROGRESS_PRINTED);
> 
> 
>         **printer.disconnectPrinter();**
> 
>     } catch (EscPosConnectionException e) {
>         e.printStackTrace();
>         return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_PRINTER_DISCONNECTED);
>     } catch (EscPosParserException e) {
>         e.printStackTrace();
>         return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_PARSER_ERROR);
>     } catch (EscPosEncodingException e) {
>         e.printStackTrace();
>         return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_ENCODING_ERROR);
>     } catch (EscPosBarcodeException e) {
>         e.printStackTrace();
>         return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_BARCODE_ERROR);
>     } catch (InterruptedException e) {
>         e.printStackTrace();
>     }
>     return new PrinterStatus(printerData, AsyncEscPosPrint.FINISH_SUCCESS);
> }
> ```

this solution worked at all? or its just a false positive?
