### ISSUE TITLE
isConnected failed: ECONNREFUSED (Connection refused)

### ISSUE THREAD

**Issue by RepublicanSensei** [DantSu/ESCPOS-ThermalPrinter-Android#391]
Hello, I am having this issue and I do not know how to fix it.
Same WiFi adress with thermal printer.

`W/System.err: java.net.ConnectException: failed to connect to /192.168.5.140 (port 9100) from /192.168.5.140 (port 34098) after 15ms: isConnected failed: ECONNREFUSED (Connection refused)
W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:287)
W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:134)
W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
W/System.err:     at java.net.Socket.connect(Socket.java:631)
W/System.err:     at com.dantsu.escposprinter.connection.tcp.TcpConnection.connect(TcpConnection.java:63)
W/System.err:     at com.dantsu.escposprinter.connection.tcp.TcpConnection.connect(TcpConnection.java:12)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinterCommands.connect(EscPosPrinterCommands.java:301)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:54)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:27)
W/System.err:     at com.nhtdllc.autoprint.OrderDetails$1$1.run(OrderDetails.java:90)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
W/System.err: Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:274)
W/System.err: 	... 15 more
W/System.err: com.dantsu.escposprinter.exceptions.EscPosConnectionException: Unable to connect to TCP device.
W/System.err:     at com.dantsu.escposprinter.connection.tcp.TcpConnection.connect(TcpConnection.java:69)
W/System.err:     at com.dantsu.escposprinter.connection.tcp.TcpConnection.connect(TcpConnection.java:12)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinterCommands.connect(EscPosPrinterCommands.java:301)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:54)
W/System.err:     at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:27)
W/System.err:     at com.nhtdllc.autoprint.OrderDetails$1$1.run(OrderDetails.java:90)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
`

**Comment by shehanGuruge** [comment]
I am also getting the same issue? Is there a way to solve this?

**Comment by DantSu** [comment]
`W/System.err: java.net.ConnectException: failed to connect to /192.168.5.140 (port 9100) from /192.168.5.140 (port 34098) `

Have you try to use `127.0.0.1` instead of `192.168.5.140` ?

**Comment by RepublicanSensei** [comment]
> 127.0.0.1

Yes I tried and It didnt work.

**Comment by RepublicanSensei** [comment]
Printer's IP is 192.168.5.126
Default Gateway is 192.168.5.1
We are connected to same WiFi

`                           EscPosPrinter printer = new EscPosPrinter(new TcpConnection(MainActivity.UserPrinterIP, 9100, 15), 203, 48f, 32);
                            printer
                                    .printFormattedText(
                                            //"[C]<img>" + PrinterTextParserImg.bitmapToHexadecimalString(printer, getApplicationContext().getResources().getDrawableForDensity(R.drawable.logo, DisplayMetrics.DENSITY_MEDIUM)) + "</img>\n" +
                                            "[L]\n" +
                                                    "[C]<u><font size='big'>" + Order.OrderRestaurantName() + "</font></u>\n" +
                                                    "[L]\n" +
                                                    "[C]================================\n" +
                                                    "[L]\n" +
                                                    Items.toString() +
                                                    "[C]--------------------------------\n" +
                                                    "[L]PAYMENT TYPE :" + finalPaymentType + "\n" +
                                                    "[R]TOTAL PRICE :[R]" + Order.orderTotal() + "\n" +
                                                    //"[R]TAX :[R]4.23e\n" +
                                                    "[L]\n" +
                                                    "[C]================================\n" +
                                                    "[L]\n" +
                                                    "[L]<font size='tall'>Customer :</font>\n" +
                                                    "[L]" + TargetOrder + "\n" +
                                                    "[L]Thank you for ordering from us!\n" +
                                                    "[L]-\n" +
                                                    "[L]-\n" +
                                                    "[L]\n" +
                                                    //"[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
                                                    "[C]<qrcode size='20'>https://www.nhtdwebsolutions.com/</qrcode>"
                                    );`

**Comment by DantSu** [comment]
`java.net.ConnectException: failed to connect to /192.168.5.140 (port 9100) from /192.168.5.140 (port 34098)`

In the error, it's try to connect to same ip of your android device.  I can't help you, sorry

**Comment by RepublicanSensei** [comment]
> `java.net.ConnectException: failed to connect to /192.168.5.140 (port 9100) from /192.168.5.140 (port 34098)`
> 
> In the error, it's try to connect to same ip of your android device. I can't help you, sorry

Yes, because they both are connected to same WiFi

**Comment by RepublicanSensei** [comment]
Please help me.

**Comment by DantSu** [comment]
I can't, I don't have the full config of your local network and it's may be a network config problem. Firewall, proxy...

**Comment by shehanGuruge** [comment]
@RepublicanSensei are you sure the printer ip is correct at the moment? Or else try to connect with it manually using a third party software or implementing a socket communication by yourself to verify.

@DantSu does it usually takes time to communicate using ethernet. For example, when try to print the receipt as soon as I switch on the printer (connected to the router), I also get the above error. But after waiting for around 15s it works without any issue. So is it like a common behavior?

**Comment by Yader1** [comment]
Good afternoon, I get this error when trying to print several invoices, what happens is that the method that connects since I couldn't find it, what I have to do is clean the existing connections and reconnect it.

`public DeviceConnection getPrinterDesco() {
        return this.printerConnection.disconnect();
}`

and in the AsyncTcpEscPosPrint we disconnect by calling the method that we have created in AsyncEscPosPrinter.
If this error is due to a connection, sometimes it persists a lot and the ideal is to clean the existing connections.
