### ISSUE TITLE
App not working with Jetpack compose, Kotlin & X-Printer XP-P300 

### ISSUE THREAD

**Issue by Ngugs** [DantSu/ESCPOS-ThermalPrinter-Android#440]
This is a simple app using the latest version of Android Studio Flamingo 2022.2.1 with Jetpack compose in Kotlin. 
[Github link](https://github.com/Ngugs/Toothx)

Tested with x-printer mobile printer. App hangs and cannot continue when I press button. Main error is : 

com.dantsu.escposprinter.exceptions.EscPosConnectionException: Unable to connect to bluetooth device.

Error message is:

`ava.io.IOException: read failed, socket might closed or timeout, read ret: -1
2023-08-15 16:42:00.408  9211-9211  System.err              com.almasi.toothx                    W  	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:776)
2023-08-15 16:42:00.408  9211-9211  System.err              com.almasi.toothx                    W  	at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:790)
2023-08-15 16:42:00.408  9211-9211  System.err              com.almasi.toothx                    W  	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:415)
2023-08-15 16:42:00.408  9211-9211  System.err              com.almasi.toothx                    W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:72)
2023-08-15 16:42:00.408  9211-9211  System.err              com.almasi.toothx                    W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
2023-08-15 16:42:00.408  9211-9211  System.err              com.almasi.toothx                    W  	at com.almasi.toothx.MainActivityKt.print(MainActivity.kt:105)
2023-08-15 16:42:00.408  9211-9211  System.err              com.almasi.toothx                    W  	at com.almasi.toothx.MainActivityKt$Greeting$1$1.invoke(MainActivity.kt:86)
2023-08-15 16:42:00.408  9211-9211  System.err              com.almasi.toothx                    W  	at com.almasi.toothx.MainActivityKt$Greeting$1$1.invoke(MainActivity.kt:77)
2023-08-15 16:42:00.409  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:167)
2023-08-15 16:42:00.409  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:156)
2023-08-15 16:42:00.409  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:234)
2023-08-15 16:42:00.409  9211-9211  System.err              com.almasi.toothx                    W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-08-15 16:42:00.409  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
2023-08-15 16:42:00.409  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
2023-08-15 16:42:00.409  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
2023-08-15 16:42:00.409  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
2023-08-15 16:42:00.410  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
2023-08-15 16:42:00.410  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
2023-08-15 16:42:00.410  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:566)
2023-08-15 16:42:00.410  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:456)
2023-08-15 16:42:00.410  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:469)
2023-08-15 16:42:00.410  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:394)
2023-08-15 16:42:00.410  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:314)
2023-08-15 16:42:00.410  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
2023-08-15 16:42:00.410  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
2023-08-15 16:42:00.410  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
2023-08-15 16:42:00.411  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
2023-08-15 16:42:00.411  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:98)
2023-08-15 16:42:00.411  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1329)
2023-08-15 16:42:00.411  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1275)
2023-08-15 16:42:00.411  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1214)
2023-08-15 16:42:00.411  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
2023-08-15 16:42:00.411  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2823)
2023-08-15 16:42:00.411  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
2023-08-15 16:42:00.411  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2823)
2023-08-15 16:42:00.412  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
2023-08-15 16:42:00.412  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2823)
2023-08-15 16:42:00.412  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
2023-08-15 16:42:00.412  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2823)
2023-08-15 16:42:00.412  9211-9211  System.err              com.almasi.toothx                    W  	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
2023-08-15 16:42:00.412  9211-9211  System.err              com.almasi.toothx                    W  	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
2023-08-15 16:42:00.412  9211-9211  System.err              com.almasi.toothx                    W  	at android.app.Activity.dispatchTouchEvent(Activity.java:4195)
2023-08-15 16:42:00.412  9211-9211  System.err              com.almasi.toothx                    W  	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
2023-08-15 16:42:00.412  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.View.dispatchPointerEvent(View.java:14837)
2023-08-15 16:42:00.413  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6590)
2023-08-15 16:42:00.413  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6382)
2023-08-15 16:42:00.413  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5856)
2023-08-15 16:42:00.413  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5913)
2023-08-15 16:42:00.413  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5879)
2023-08-15 16:42:00.413  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6044)
2023-08-15 16:42:00.413  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5887)
2023-08-15 16:42:00.413  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6101)
2023-08-15 16:42:00.413  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5860)
2023-08-15 16:42:00.414  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5913)
2023-08-15 16:42:00.414  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5879)
2023-08-15 16:42:00.414  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5887)
2023-08-15 16:42:00.414  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5860)
2023-08-15 16:42:00.414  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8931)
2023-08-15 16:42:00.414  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8871)
2023-08-15 16:42:00.414  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8828)
2023-08-15 16:42:00.414  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9063)
2023-08-15 16:42:00.414  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
2023-08-15 16:42:00.415  9211-9211  System.err              com.almasi.toothx                    W  	at android.os.MessageQueue.nativePollOnce(Native Method)
2023-08-15 16:42:00.415  9211-9211  System.err              com.almasi.toothx                    W  	at android.os.MessageQueue.next(MessageQueue.java:335)
2023-08-15 16:42:00.415  9211-9211  System.err              com.almasi.toothx                    W  	at android.os.Looper.loopOnce(Looper.java:161)
2023-08-15 16:42:00.415  9211-9211  System.err              com.almasi.toothx                    W  	at android.os.Looper.loop(Looper.java:288)
2023-08-15 16:42:00.415  9211-9211  System.err              com.almasi.toothx                    W  	at android.app.ActivityThread.main(ActivityThread.java:7886)
2023-08-15 16:42:00.415  9211-9211  System.err              com.almasi.toothx                    W  	at java.lang.reflect.Method.invoke(Native Method)
2023-08-15 16:42:00.415  9211-9211  System.err              com.almasi.toothx                    W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
2023-08-15 16:42:00.415  9211-9211  System.err              com.almasi.toothx                    W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2023-08-15 16:42:00.416  9211-9211  BluetoothSocket         com.almasi.toothx                    D  close() this: android.bluetooth.BluetoothSocket@3468c7e, channel: -1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@b4c65df, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@b822cmSocket: android.net.LocalSocket@9804f5 impl:android.net.LocalSocketImpl@cbaf28a fd:java.io.FileDescriptor@23b80fb, mSocketState: INIT
2023-08-15 16:42:00.417  9211-9211  System.err              com.almasi.toothx                    W  com.dantsu.escposprinter.exceptions.EscPosConnectionException: Unable to connect to bluetooth device.
2023-08-15 16:42:00.418  9211-9211  System.err              com.almasi.toothx                    W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:78)
2023-08-15 16:42:00.418  9211-9211  System.err              com.almasi.toothx                    W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
2023-08-15 16:42:00.418  9211-9211  System.err              com.almasi.toothx                    W  	at com.almasi.toothx.MainActivityKt.print(MainActivity.kt:105)
2023-08-15 16:42:00.418  9211-9211  System.err              com.almasi.toothx                    W  	at com.almasi.toothx.MainActivityKt$Greeting$1$1.invoke(MainActivity.kt:86)
2023-08-15 16:42:00.418  9211-9211  System.err              com.almasi.toothx                    W  	at com.almasi.toothx.MainActivityKt$Greeting$1$1.invoke(MainActivity.kt:77)
2023-08-15 16:42:00.418  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:167)
2023-08-15 16:42:00.418  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:156)
2023-08-15 16:42:00.418  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:234)
2023-08-15 16:42:00.419  9211-9211  System.err              com.almasi.toothx                    W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-08-15 16:42:00.419  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
2023-08-15 16:42:00.419  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
2023-08-15 16:42:00.419  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
2023-08-15 16:42:00.419  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
2023-08-15 16:42:00.419  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
2023-08-15 16:42:00.419  9211-9211  System.err              com.almasi.toothx                    W  	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
2023-08-15 16:42:00.419  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:566)
2023-08-15 16:42:00.419  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:456)
2023-08-15 16:42:00.420  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:469)
2023-08-15 16:42:00.420  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:394)
2023-08-15 16:42:00.420  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:314)
2023-08-15 16:42:00.420  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
2023-08-15 16:42:00.420  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
2023-08-15 16:42:00.420  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
2023-08-15 16:42:00.421  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
2023-08-15 16:42:00.421  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:98)
2023-08-15 16:42:00.421  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1329)
2023-08-15 16:42:00.421  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1275)
2023-08-15 16:42:00.421  9211-9211  System.err              com.almasi.toothx                    W  	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1214)
2023-08-15 16:42:00.421  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
2023-08-15 16:42:00.421  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2823)
2023-08-15 16:42:00.421  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
2023-08-15 16:42:00.422  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2823)
2023-08-15 16:42:00.422  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
2023-08-15 16:42:00.422  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2823)
2023-08-15 16:42:00.422  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
2023-08-15 16:42:00.422  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2823)
2023-08-15 16:42:00.422  9211-9211  System.err              com.almasi.toothx                    W  	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
2023-08-15 16:42:00.422  9211-9211  System.err              com.almasi.toothx                    W  	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
2023-08-15 16:42:00.422  9211-9211  System.err              com.almasi.toothx                    W  	at android.app.Activity.dispatchTouchEvent(Activity.java:4195)
2023-08-15 16:42:00.423  9211-9211  System.err              com.almasi.toothx                    W  	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
2023-08-15 16:42:00.423  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.View.dispatchPointerEvent(View.java:14837)
2023-08-15 16:42:00.423  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6590)
2023-08-15 16:42:00.423  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6382)
2023-08-15 16:42:00.423  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5856)
2023-08-15 16:42:00.423  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5913)
2023-08-15 16:42:00.423  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5879)
2023-08-15 16:42:00.423  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6044)
2023-08-15 16:42:00.424  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5887)
2023-08-15 16:42:00.424  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6101)
2023-08-15 16:42:00.424  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5860)
2023-08-15 16:42:00.424  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5913)
2023-08-15 16:42:00.424  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5879)
2023-08-15 16:42:00.424  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5887)
2023-08-15 16:42:00.424  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5860)
2023-08-15 16:42:00.425  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8931)
2023-08-15 16:42:00.425  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8871)
2023-08-15 16:42:00.425  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8828)
2023-08-15 16:42:00.425  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9063)
2023-08-15 16:42:00.425  9211-9211  System.err              com.almasi.toothx                    W  	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
2023-08-15 16:42:00.425  9211-9211  System.err              com.almasi.toothx                    W  	at android.os.MessageQueue.nativePollOnce(Native Method)
2023-08-15 16:42:00.425  9211-9211  System.err              com.almasi.toothx                    W  	at android.os.MessageQueue.next(MessageQueue.java:335)
2023-08-15 16:42:00.425  9211-9211  System.err              com.almasi.toothx                    W  	at android.os.Looper.loopOnce(Looper.java:161)
2023-08-15 16:42:00.425  9211-9211  System.err              com.almasi.toothx                    W  	at android.os.Looper.loop(Looper.java:288)
2023-08-15 16:42:00.425  9211-9211  System.err              com.almasi.toothx                    W  	at android.app.ActivityThread.main(ActivityThread.java:7886)
2023-08-15 16:42:00.426  9211-9211  System.err              com.almasi.toothx                    W  	at java.lang.reflect.Method.invoke(Native Method)
2023-08-15 16:42:00.426  9211-9211  System.err              com.almasi.toothx                    W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
2023-08-15 16:42:00.426  9211-9211  System.err              com.almasi.toothx                    W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)`

**Comment by herdumundo** [comment]
its working for me in Jetpack Compose.
