### ISSUE TITLE
Connection Exception when printing

### ISSUE THREAD

**Issue by Joealtidore1** [DantSu/ESCPOS-ThermalPrinter-Android#494]
I am using Xprinter model XP-P502A.
Whenever I attempt printing, I get the stacktrace below

`java.io.IOException: read failed, socket might closed or timeout, read ret: -1
	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:776)
	at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:790)
	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:415)
	at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:69)
	at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
close() this: android.bluetooth.BluetoothSocket@d46d890, channel: -1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@c864589, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@f51898emSocket: android.net.LocalSocket@f7505af impl:android.net.LocalSocketImpl@e8edbc fd:java.io.FileDescriptor@704b145, mSocketState: INIT
com.dantsu.escposprinter.exceptions.EscPosConnectionException: Unable to connect to bluetooth device.
	at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:75)
	at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:26)...`

**Comment by devparanhos** [comment]
Same here, it onl prints after a few attempts

**Comment by Azeem00786** [comment]
i am also getting the same for blueprints printer with samsung device.

**Comment by devparanhos** [comment]
I resolved that always disconnect the printer after printing and also set Dispatcher.IO for this type of thread.

**Comment by Azeem00786** [comment]
I have already disconnected the printer after printing. This issue is happening with a few devices. It starts working when I unpair all the other devices and pair only my printer. However, I am searching for the root cause because I know the fault will be on my side.
![image](https://github.com/user-attachments/assets/147061ea-e2e2-45ba-a864-845168a797e5)
