### ISSUE TITLE
prints normally for first time then third time, but in second time not printing

### ISSUE THREAD

**Issue by etman55** [DantSu/ESCPOS-ThermalPrinter-Android#66]

**Comment by DantSu** [comment]
If you try to reset the printer. May be it will solve the problem.

```java
TcpConnection printerConnection = new TcpConnection(PrinterConstants.IP, PrinterConstants.PORT);
EscPosPrinter printer = new EscPosPrinter(printerConnection, 203, 56f, 48, new EscPosCharsetEncoding("windows-1252", 16));

printerConnection.write(new byte[] {0x1B, 0x40});
printerConnection.send();
printer.printFormattedText("[R]TEST 1\n");
printerConnection.write(new byte[] {0x1B, 0x40});
printerConnection.send();
printer.printFormattedText("[R]TEST 2\n");
printerConnection.write(new byte[] {0x1B, 0x40});
printerConnection.send();
printer.printFormattedText("[R]TEST 3\n");
```

**Comment by etman55** [comment]
I am using bluetooth connection not tcp

**Comment by DantSu** [comment]
use the printerConnection instance. not matter if is bluetooth or tcp or usb.

**Comment by etman55** [comment]
Here is my code for printing
```
                val printerConnection = BluetoothPrintersConnections.selectFirstPaired()
                val printer = EscPosPrinter(printerConnection, 203, 48f, 32)
                printerConnection.write(byteArrayOf(0x1B, 0x40))
                printerConnection.send()
                printer.printFormattedText(
                    "[C]<img>${PrinterTextParserImg.bitmapToHexadecimalString(
                        printer,
                        resources.getDrawableForDensity(
                            R.drawable.im_printlogo, DisplayMetrics.DENSITY_LOW
                        )
                    )}</img>"
                )
                printerConnection.write(byteArrayOf(0x1B, 0x40))
                printerConnection.send()
                printer.printFormattedTextAndCut(headTxt + tableTxt)
```
and this is the log i get
```2020-10-05 11:14:33.422 9894-10401/com.afaqy.sa.driver W/BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
2020-10-05 11:14:33.475 9894-10401/com.afaqy.sa.driver W/System.err: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:772)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:725)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:409)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:66)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:23)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at com.afaqy.sa.driver.ui.print.PrintFragment$launchPrintReceipt$6.invokeSuspend(PrintFragment.kt:230)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
2020-10-05 11:14:33.476 9894-10401/com.afaqy.sa.driver W/System.err: com.dantsu.escposprinter.exceptions.EscPosConnectionException: Unable to connect to bluetooth device.
2020-10-05 11:14:33.477 9894-10401/com.afaqy.sa.driver W/System.err:     at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:73)
2020-10-05 11:14:33.477 9894-10401/com.afaqy.sa.driver W/System.err:     at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired(BluetoothPrintersConnections.java:23)
2020-10-05 11:14:33.477 9894-10401/com.afaqy.sa.driver W/System.err:     at com.afaqy.sa.driver.ui.print.PrintFragment$launchPrintReceipt$6.invokeSuspend(PrintFragment.kt:230)
2020-10-05 11:14:33.477 9894-10401/com.afaqy.sa.driver W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-10-05 11:14:33.477 9894-10401/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
2020-10-05 11:14:33.477 9894-10401/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
2020-10-05 11:14:33.477 9894-10401/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
2020-10-05 11:14:33.477 9894-10401/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
2020-10-05 11:14:33.517 9894-9894/com.afaqy.sa.driver W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.write(byte[])' on a null object reference
2020-10-05 11:14:33.517 9894-9894/com.afaqy.sa.driver W/System.err:     at com.afaqy.sa.driver.ui.print.PrintFragment$launchPrintReceipt$6.invokeSuspend(PrintFragment.kt:232)
2020-10-05 11:14:33.517 9894-9894/com.afaqy.sa.driver W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-10-05 11:14:33.517 9894-9894/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
2020-10-05 11:14:33.517 9894-9894/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
2020-10-05 11:14:33.517 9894-9894/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
2020-10-05 11:14:33.517 9894-9894/com.afaqy.sa.driver W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)```

**Comment by DantSu** [comment]
I can explain this error. I will investigate but I have'nt enought time .

**Comment by kelbongoo** [comment]
I'm also getting this error

**Comment by DantSu** [comment]
paste me your full error message please

**Comment by kelbongoo** [comment]
Thanks for a rapid reply !
I was able to resolve the problem by calling printer.printFormattedTextAndCut() instead of

printer
    .printFormattedText(text);

printerConnection.write(CUT_PAPER);
printerConnection.send();

My original code is clearly blocking the buffer somehow.
Thanks again :)
