### ISSUE TITLE
Exception when printing formatted text: java.lang.StringIndexOutOfBoundsException: length=0; index=3

### ISSUE THREAD

**Issue by livotov** [DantSu/ESCPOS-ThermalPrinter-Android#73]
The following data 
```
[L]<b>Mars Ltd.</b>
[L]Tax No. - 000000000N
[L]0000 Upper Lower Road
[L]#01-1234
[L]Mars 008888
[L]Phone - (99) 88888888
[L]Fax - (99) 88888888
[L]VAT Reg. No. : 000000000N
[L]
[C]<font size='big'>TAX INVOICE</font>
[L]
[L]Invoice No: HQ60010462[R]Date: 27/10/2020
[L]Terms: COD[R]Time: 18:00:00
[L]Salesman: E[R]Delivery: 27/10/2020
[C]-------------------------------
[L]S.No Desc.[L]Qty [L]Price [R]Amount
[C]-------------------------------
[L]1. 100 Pl[L]x6[L]$12.00[R]$72.00
[L]2. 3 Rose[L]x6[L]$192.00[R]$1,152.00
[L]3. Alamo [L]x6[L]$4.56[R]$27.36
[C]-------------------------------
[L]Qty: 3[R]Total: $1,251.36
[R]Discount: $0.00
[R]VAT: $87.60
[R]----------
[R]Net Total: $1,338.96
```

results in an exception when printing:

```
java.lang.StringIndexOutOfBoundsException: length=0; index=3
at java.lang.String.substring(String.java:2060)
at com.dantsu.escposprinter.textparser.PrinterTextParserColumn.<init>(PrinterTextParserColumn.java:40)
at com.dantsu.escposprinter.textparser.PrinterTextParserLine.<init>(PrinterTextParserLine.java:46)
at com.dantsu.escposprinter.textparser.PrinterTextParser.parse(PrinterTextParser.java:173)
at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:106)
at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:88)
at com.dantsu.escposprinter.EscPosPrinter.printFormattedText(EscPosPrinter.java:77)
```

The interesting part is that if I remove those 3 lines it prints successfully. 

```
[L]1. 100 Pl[L]x6[L]$12.00[R]$72.00
[L]2. 3 Rose[L]x6[L]$192.00[R]$1,152.00
[L]3. Alamo [L]x6[L]$4.56[R]$27.36
```

Alternatively, I can remove everything below those 3 lines and it prints normally again.

Can't figure out what is wrong. Any ideas?

Using the v2.0.6 of the library.

**Comment by livotov** [comment]
Just FYI - my template engine inserted an extra \n character after the "[L]3. Alamo [L]x6[L]$4.56[R]$27.36" string (last string in a loop iteration) and it looks like PrintTextParser cannot process empty lines.

To simplify (just 2 lines, without the template processor):

This one works:
```
[L]Line 1
[L]Line 2
```

This one does not with the same StringIndexOutOfBoundsException: length=0; index=3 error:
```
[L]Line 1

[L]Line 2
```

**Comment by DantSu** [comment]
I add this issue to the TO DO list. Thx for this report.

**Comment by DantSu** [comment]
v2.0.8 is out. This issue is fixed.
